import { Inter } from "next/font/google";
import "./globals.css";
import "animate.css";
import TheFooter from "./components/TheFooter";
import { Analytics } from "@vercel/analytics/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`min-h-svh w-screen max-w-full flex flex-col mx-auto relative ${inter.className} antialiased`}
      >
        {children}
        <TheFooter />
        <Analytics />
      </body>
    </html>
  );
}
